name: Deploy to Netlify Hosting on main merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: 🧰 Install Dependencies
        run: yarn install
      - name: 📦 Build Project
        run: yarn build
      - name: 🧹 Run Lint
        run: yarn lint
      - name: 🐛 Run Tests
        run: yarn test
        env:
          REACT_APP_BITQUERY: ${{ secrets.REACT_APP_BITQUERY }}
          REACT_APP_GETBLOCK: ${{ secrets.REACT_APP_GETBLOCK }}
          REACT_APP_BCONNECT: ${{ secrets.REACT_APP_BCONNECT }}
          REACT_APP_BCONNECT_URL: ${{ secrets.REACT_APP_BCONNECT_URL }}
      - name: 🚀 Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
